addSbtPlugin("org.scalameta" % "sbt-mdoc"       % "2.2.21")
addSbtPlugin("org.scalameta" % "sbt-scalafmt"   % "2.4.2")
addSbtPlugin("com.eed3si9n"  % "sbt-unidoc"     % "0.4.3")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix"   % "0.9.29")
addSbtPlugin("com.geirsson"  % "sbt-ci-release" % "1.5.7")
